[package]
name = "grida-fx-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
grida-fx-core.workspace = true
grida-fx-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
indexmap.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
