[package]
name = "grida-fx"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "grida-fx"
path = "src/main.rs"

[dependencies]
grida-fx-core.workspace = true
grida-fx-protocol.workspace = true
grida-fx-runtime.workspace = true
grida-fx-providers.workspace = true
grida-fx-viewer.workspace = true
tokio.workspace = true
serde_json.workspace = true
indexmap.workspace = true
clap.workspace = true

[dev-dependencies]
tempfile.workspace = true
jsonschema.workspace = true

[lints]
workspace = true
